---
  - name: Kubernetes Setup | Node Join
    block:
      - name: Kubernetes Setup | Node Join | Gather Node Joining Details
        command: "kubeadm token create  --print-join-command"
        register: kubernetes_join_command
        run_once: true
        no_log: true
        delegate_to: "master"
      - name: Kubernetes Setup | Node Join | Add node to cluster
        shell: "{{ kubernetes_join_command.stdout }} --node-name {{ ansible_hostname }}"
        become: true

  - name: Kubernetes Setup | Node Configuration
    block:
      - name: Kubernetes Setup | Node Configuration | Create .kube directory
        file:
          path: "{{ ansible_env.HOME }}/.kube"
          state: directory
      - name: Kubernetes Setup | Node Configuration | Copy kube config
        copy:
          src: "{{ vagrant.config_path }}/config"
          dest: "{{ ansible_env.HOME }}/.kube/config"
          remote_src: true
          owner: "{{ ansible_env.USER }}"
          group: "{{ ansible_env.USER }}"
        become: true
      - name: Kubernetes Setup | Node Configuration | Update Node role
        shell: kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker=worker