---
  - name: Docker Setup | APT
    block:
      - name: Docker Setup | APT | Configure Repository | Add docker repository key
        apt_key:
          url: "{{ item.url }}"
          keyring: "{{ item.keyring }}"
          state: present
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"
        with_items:
          - url: "https://download.docker.com/linux/ubuntu/gpg"
            keyring: /etc/apt/keyrings/docker.gpg

      - name: Docker Setup | APT | Get DEB architecture
        shell: dpkg --print-architecture
        register: deb_architecture

      - name: Docker Setup | APT | Configure Repository | Add docker repository
        apt_repository:
          repo: "{{ item.repo }}"
          filename: "{{ item.filename }}"
          state: present
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"
        with_items:
          - repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            filename: /etc/apt/sources.list.d/docker.list
      - name: Docker Setup | APT | Install required packages
        apt:
          pkg: "{{ docker.packages }}"
          update_cache: yes
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"


  - name: Docker Setup | Service
    block:
      - name: Docker Configuration | Configure data path of docker
        copy:
          dest: "/etc/docker/daemon.json"
          content: |
            {
               "data-root": "{{ docker.data_dir }}"
            }
        become: true
        notify: "docker service restart"


  - name: Docker Setup | Kubernetes Configuration
    block:
      - name: Docker Setup | Kubernetes Configuration | Backup kubernetes service file
        copy:
          src: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf.bkp
          remote_src: yes
        become: true
      - name: Docker Setup | Kubernetes Configuration | Gather Dockers Cgroup Driver
        shell: |
            docker info 2>/dev/null | sed -n 's/Cgroup Driver: \(.*\)/\1/p'
        register: docker_cgroup_driver
        become: true
      - name: Docker Setup | Kubernetes Configuration | Add cgroup-driver Environment variable in kubeadm service file
        lineinfile:
          path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          insertafter: '^Environment='
          line: 'Environment="KUBELET_CGROUP_ARGS=--cgroup-driver={{ docker_cgroup_driver.stdout | trim }}"'
        become: true
      - name: Docker Setup | Kubernetes Configuration | Pass cgroup-driver parameter to kubelet binary
        lineinfile:
          path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          backrefs: yes
          regexp: '^(ExecStart=\/usr\/bin\/kubelet(.*)$)'
          line: '\1 $KUBELET_CGROUP_ARGS'
        become: true
      - name: Docker Setup | Kubernetes Configuration | Backup containerd config file
        copy:
          remote_src: true
          src: /etc/containerd/config.toml
          dest: /etc/containerd/config.toml.bkp
        become: true
      - name: Docker Setup | Kubernetes Configuration | Configure containerd config file
        file:
          path: /etc/containerd/config.toml
          state: absent
        become: true
        notify: "containerd service restart"
