---
  - name: Kubernetes Setup | APT
    block:
      - name: Kubernetes Setup | APT | Configure Repository | Add Kubernetes repository key
        apt_key:
          url: "{{ item.url }}"
          keyring: "{{ item.keyring }}"
          state: present
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"
        with_items:
          - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      - name: Kubernetes Setup | APT | Configure Repository | Add Kubernetes repository
        apt_repository:
          repo: "{{ item.repo }}"
          filename: "{{ item.filename }}"
          state: present
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"
        with_items:
          - repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
            filename: /etc/apt/sources.list.d/kubernetes.list
      - name: Kubernetes Setup | APT | Install required packages
        apt:
          pkg:
            - kubelet={{ kubernetes.version }}
            - kubectl={{ kubernetes.version }}
            - kubeadm={{ kubernetes.version }}
          update_cache: yes
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"


  - name: Kubernetes Setup | Service
    block:
      - name: Kubernetes Setup | Service | Configure
        copy:
          dest: "/etc/default/kubelet"
          content: |
            KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}
        become: true