---
  - name: System Setup | APT
    block:
      - name: System Setup | APT | Update Repo and Cache
        apt:
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"
#      - name: System Setup | APT | Upgrade all packages
#        apt:
#          upgrade: dist
#          force_apt_get: yes
#        become: true
      - name: System Setup | APT | Install System setup packages
        apt:
          pkg:
            - toilet
            - lolcat
            - figlet
            - fortune
            - cowsay
            - apt-transport-https
            - ca-certificates
            - curl
          state: present
        become: true
        register: result
        retries: 3
        delay: 5
        until: "result is not failed"


  - name: System Setup | HOST
    block:
      - name: System Setup | HOST | Reset Hostname Configuration
        hostname:
          name: "kube-{{ ansible_eth1.ipv4.address | replace('.','') | reverse }}.{{ domain }}"
        become: true


  - name: System Setup | SSH
    block:
      - name: System Setup | SSH | Setup SSH Banner
        lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: 'Banner'
          line: "Banner /etc/issue.net"
        become: true
      - name: System Setup | SSH | Update SSH Banner
        shell: |
          toilet -f term  -w 102 'Welcome to ....' | tee /etc/issue > /etc/issue.net
          toilet -f mono12 -F border -w 500 "{{ domain | upper }}" | tee -a /etc/issue >> /etc/issue.net
          toilet -f term  -w 102 "$(hostname)" | tee -a /etc/issue >> /etc/issue.net
          toilet -f term  -w 102 'ALERT! You are entering into a secured area! Your IP, Login Time, Username has been noted and has been sent to the server administrator! This service is restricted to authorized users only. All activities on this system are logged. Unauthorized access will be fully investigated and reported to the appropriate law enforcement agencies.' | tee -a /etc/issue >> /etc/issue.net
        become: true
      - name: System Setup | SSH | Restart ssh
        service:
          name: ssh
          state: restarted
        become: true


  - name: System Setup | Swap
    block:
      - name: System Setup | Swap | Disable SWAP since kubernetes can't work with swap enabled (1/2)
        shell: |
          swapoff -a
        become: true
      - name: System Setup | Swap | Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
        replace:
          path: /etc/fstab
          regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
          replace: '# \1'
        become: true