apiVersion: v1
kind: Service
metadata:
  name: nginxsvc-wd
  labels:
    app: nginx-wd
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-wd
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: relica-controller-wd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-wd
    spec:
      containers:
      - name: nginx-wd
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-data
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
      - name: nginx-data
        hostPath:
          path: /data