---
  - name: Disk Setup | Install parted
    package:
      name: parted
      state: present
    become: true

  - name: Disk Setup | Fetch disk name
    shell: |
        fdisk -l | grep Disk | grep -E '(vdb:|sdb:)' | cut -d" " -f2 | cut -d":" -f1
    become: true
    register: disk_name

  - name: Disk Setup | Sync Disk/Fix GPT PMBR size mismatch
    shell: |
      (
        echo w # Write changes
      ) | sudo fdisk {{ disk_name.stdout }}
    become: true

  - name: Disk Setup | Create Filesystem
    filesystem:
      fstype: "{{ disk_part.fs }}"
      dev: "{{ disk_name.stdout }}"
    become: true

  - name: Disk Setup | Mount Partition
    mount:
      fstype: "{{ disk_part.fs }}"
      src: "{{ disk_name.stdout }}"
      path: "{{ disk_part.mount }}"
      state: mounted
    become: true