---
# tasks file for ansible-nfs-server
  - name: Set Facts
    include_tasks: set-facts.yml

  - name: Disk Setup
    include_tasks: disk_part.yml
    when: disk_part.create

  - name: Debian Installation
    include_tasks: debian.yml
    when: ansible_os_family == "Debian"

  - name: Redhat Installation
    include_tasks: redhat.yml
    when: ansible_os_family == "RedHat"

  - name: Configure
    include_tasks: config.yml
