---
# tasks file for ansible-nfs-server
  - name: Set Facts
    include: set-facts.yml

  - name: Disk Setup
    include: disk_part.yml
    when: disk_part.create

  - name: Debian Installation
    include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Redhat Installation
    include: redhat.yml
    when: ansible_os_family == "RedHat"

  - name: Configure
    include: config.yml
