---
  docker_data_path: '/data/docker'
  required_packages:
    - docker.io
    - vim
    - apt-transport-https
    - curl
    - openssh-server
    - kubelet
    - kubeadm
    - kubectl
  domain: jackson.com
