- name: Node-Pod SNAT MASQUERADE
  block:
    - name: Node-Pod SNAT MASQUERADE | Upload Daemonset Config
      template:
        src: network_masquerader_ds.yaml.j2
        dest: "{{ ansible_env.HOME }}/.kube/network_masquerader_ds.yaml"
    - name: Node-Pod SNAT MASQUERADE | Apply Daemonset Config
      shell: "kubectl apply -f {{ ansible_env.HOME }}/.kube/network_masquerader_ds.yaml"
  when: kubernetes.cluster_cidr is defined