---
# defaults file for common
system:
  domain: "jackson.com"
crio:
  os: "xUbuntu_20.04"
  version: "1.23"
  data_dir: "/data/docker"
  kernel_module:
    - overlay
    - br_netfilter
  sysctl:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { name: 'net.ipv4.ip_forward', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
  packages:
    - cri-o
    - cri-o-runc
kubernetes:
  version: "1.25.0-00"