---
  - name: Reset old Kubernetes Cluster if exist
    block:
      - name: Reset old Cluster | Remove kubernetes clusters
        shell: "kubeadm reset -f"
        ignore_errors: true
        become: true
      - name: Reset old Cluster | Install host setup packages
        apt:
          pkg:
            - toilet
            - lolcat
            - figlet
            - fortune
            - cowsay
          state: present
        become: true
      - name: Reset old Cluster | setup login Banner
        lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: 'Banner'
          line: "Banner /etc/issue.net"
        become: true
      - name: Reset old Cluster | Update ssh banner
        shell: |
          toilet -f term  -w 102 'Welcome to ....' | tee /etc/issue > /etc/issue.net
          toilet -f mono12 -F border -w 500 'JACKSON.COM' | tee -a /etc/issue >> /etc/issue.net
          toilet -f term  -w 102 "kube-{{ hostvars[inventory_hostname].group_names[0] }}-{{ ansible_default_ipv4.address | replace('.','') | reverse }}.{{ domain }}" | tee -a /etc/issue >> /etc/issue.net
          toilet -f term  -w 102 'ALERT! You are entering into a secured area! Your IP, Login Time, Username has been noted and has been sent to the server administrator! This service is restricted to authorized users only. All activities on this system are logged. Unauthorized access will be fully investigated and reported to the appropriate law enforcement agencies.' | tee -a /etc/issue >> /etc/issue.net
        become: true
      - name: Reset old Cluster | Restart ssh
        service:
          name: ssh
          state: restarted
        become: true
      - name: Reset old Cluster | Reset Hostname Configuration
        hostname:
          name: "kube-{{ hostvars[inventory_hostname].group_names[0] }}-{{ ansible_default_ipv4.address | replace('.','') | reverse }}.{{ domain }}"
        become: true
      - name: Reset old Cluster | APT Configuration | Uninstall  packages
        apt:
          pkg:
            - kubeadm
            - kubelet
            - kubectl
          state: absent
          purge: true
          force: true
        become: true

  - name: Swap Configuration
    block:
      - name: Swap Configuration | Disable SWAP since kubernetes can't work with swap enabled (1/2)
        shell: |
          swapoff -a
        become: true
      - name: Swap Configuration | Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
        replace:
          path: /etc/fstab
          regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
          replace: '# \1'
        become: true

  - name: APT Configuration
    block:
      - name: APT Configuration | Configure Repository | Add kubernetes repository key
        apt_key:
          url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
          state: present
        become: true
      - name: APT Configuration | Configure Repository | Add kubernetes repository
        apt_repository:
          repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
          state: present
          filename: 'kubernetes.list'
        become: true
      - name: APT Configuration | Install required packages
        apt:
          pkg: "{{ required_packages }}"
          update_cache: yes
        become: true
      - name: APT Configuration | Hold/avoid auto upgrade of packages
        dpkg_selections:
          name: "{{ item }}"
          selection: hold
        with_items:
         - kubelet
         - kubeadm
         - kubectl
        become: true

  - name: Docker Configuration
    block:
      - name: Docker Configuration | Creates docker data directory
        file:
          path: "{{ docker_data_path }}"
          state: directory
        become: true
      - name: Docker Configuration | Configure data path of docker
        template:
          src: docker.daemon.json.j2
          dest: /etc/docker/daemon.json
        become: true
        notify: "restart docker service"

  - name: Kubernetes Configuration
    block:
      - name: Kubernetes Configuration | Backup kubernetes service file
        copy:
          src: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf.bkp
          remote_src: yes
        become: true
      - name: Kubernetes Configuration | Gather Dockers Cgroup Driver
        shell: |
            docker info 2>/dev/null | sed -n 's/Cgroup Driver: \(.*\)/\1/p'
        register: docker_cgroup_driver
        become: true
      - name: Kubernetes Configuration | Add cgroup-driver Environment variable in kubeadm service file
        lineinfile:
          path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          insertafter: '^Environment='
          line: 'Environment="KUBELET_CGROUP_ARGS=--cgroup-driver={{ docker_cgroup_driver.stdout | trim }}"'
        become: true
      - name: Kubernetes Configuration | Pass cgroup-driver parameter to kubelet binary
        lineinfile:
          path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
          backrefs: yes
          regexp: '^(ExecStart=\/usr\/bin\/kubelet(.*)$)'
          line: '\1 $KUBELET_CGROUP_ARGS'
        become: true
