---
  - name: Kubernetes Master Configuration
    block:
      - name: Kubernetes Master Configuration | Initialize cluster
        shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=192.168.0.0/16
        register: k8s_init_status
        become: true
        no_log: true
      - name: Kubernetes Master Configuration | Create .kube directory
        file:
          path: "{{ ansible_env.HOME }}/.kube"
          state: directory
      - name: Kubernetes Master Configuration | Copy admin.conf to user's kube config
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "{{ ansible_env.HOME }}/.kube/config"
          remote_src: true
          owner: "{{ ansible_env.USER }}"
          group: "{{ ansible_env.USER }}"
        become: true

  - name: Pod Network Configuration
    block:
      - name: Pod Network Configuration | Upload pod network config
        copy:
          src: calico.yaml
          dest: "{{ ansible_env.HOME }}/.kube"
      - name: Pod Network Configuration | Install Pod network
        shell: "kubectl apply -f {{ ansible_env.HOME }}/.kube/calico.yaml"
      - name: Pod Network Configuration | Set env FELIX_IGNORELOOSERPF=true to ignore unwanted errors
        shell: "kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true"

  - name: Kubernetes Dashboard Configuration
    block:
      - name: Kubernetes Dashboard Configuration | Upload dashboard config
        copy:
          src: dashboard.yaml
          dest: "{{ ansible_env.HOME }}/.kube"
      - name: Kubernetes Dashboard Configuration | Install dashboard
        shell: "kubectl apply -f {{ ansible_env.HOME }}/.kube/dashboard.yaml"

  - name: wait for pods to come up
    shell: 'kubectl wait --all-namespaces --for=condition=Ready pods --all  --timeout 600s'
    register: control_plane_pods_ready
    until: control_plane_pods_ready is not failed
    retries: 5

  - name: Post installation bug fix
    block:
      - name: Post installation bug fix | kubernrtes scheduler
        block:
          - name: Post installation bug fix | kubernrtes scheduler 1/1
            lineinfile:
              path: "{{ item }}"
              backrefs: yes
              regexp: '^([^#].*?\s+-\s+--port=0)$'
              line: '# \1'
            with_items:
              - '/etc/kubernetes/manifests/kube-scheduler.yaml'
#              - '/etc/kubernetes/manifests/kube-controller-manager.yaml'
            become: true
      - name: Post installation bug fix | restart kubelet service
        service:
          name: kubelet
          state: restarted
        become: true
      - name: Node-Pod SNAT MASQUERADE
        block:
          - name: Node-Pod SNAT MASQUERADE | Upload Daemonset Config
            template:
              src: network_masquerader_ds.yaml.j2
              dest: "{{ ansible_env.HOME }}/.kube/network_masquerader_ds.yaml"
          - name: Node-Pod SNAT MASQUERADE | Apply Daemonset Config
            shell: "kubectl apply -f {{ ansible_env.HOME }}/.kube/network_masquerader_ds.yaml"
        when: nodenetwork is defined


  - name: Dashboard Authorization Configuration
    block:
      - name: Dashboard Authorization Configuration | Create Service Account
        shell: "kubectl create serviceaccount dashboard -n default"
      - name: Dashboard Authorization Configuration | Create cluster role binding with service account
        shell: "kubectl create clusterrolebinding dashboard-admin -n default --clusterrole=cluster-admin   --serviceaccount=default:dashboard"
      - name: Dashboard Authorization Configuration | Generate Login Token
        shell: 'kubectl create token dashboard'
        register: dashboard_login_token
        no_log: true

  - name: Nginx Kube Dashboard Configuration
    block:
      - name: Nginx Kube Dashboard Configuration | Install required packages
        apt:
          pkg: "{{ required_packages }}"
          update_cache: yes
        become: true
      - name: Nginx Kube Dashboard Configuration | Create Service Account for nginx-proxy
        shell: "kubectl create serviceaccount nginx-proxy -n kube-system"
      - name: Nginx Kube Dashboard Configuration | Craete Cluster role bindinng to the Nginx proxy account
        shell: "kubectl create clusterrolebinding nginx-proxy --clusterrole=cluster-admin --serviceaccount=kube-system:nginx-proxy"
      - name: Nginx Kube Dashboard Configuration | Create Token for Nginx proxy
        shell: 'kubectl -n kube-system create token nginx-proxy'
        register: nginx_proxy_token
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Get Kubernetes Dashboard Cluster IP
        shell: "kubectl get Service -n kubernetes-dashboard kubernetes-dashboard | grep dashboard | awk '{ print $3 }'"
        register: dashboard_ip_address
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Setup Basic Auth for nginx proxy
        shell: "htpasswd -b -c {{ nginx['dashboard']['pass_file_path'] }} {{ nginx['dashboard']['admin_username'] }} {{ nginx['dashboard']['admin_password'] }}"
        become: true
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Create Certificate Directory
        file:
          path: "{{ nginx['dashboard']['cert']['path'] }}"
          state: directory
        become: true
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Generate SSL Certificate for nginx
        shell: "openssl req -new -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out {{ nginx['dashboard']['cert']['ctr'] }} -keyout {{ nginx['dashboard']['cert']['key'] }} -subj \"/C=IN/ST=MadhyaPradesh/L=Indore/O=Jackson pvt ltd/OU=Jackson/CN=*.jackson.com\""
        args:
          chdir: "{{ nginx['dashboard']['cert']['path'] }}"
        become: true
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Create Nginx Root Directory
        file:
          path: "/var/www/kube"
          state: directory
        become: true
      - name: Nginx Kube Dashboard Configuration | Copy kube admin configuration
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "/var/www/kube/config"
          remote_src: true
        become: true
        no_log: true
      - name: Nginx Kube Dashboard Configuration | Remove Default Nginx config
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/nginx/sites-enabled/default"
          - "/etc/nginx/sites-available/default"
        become: true
      - name: Nginx Kube Dashboard Configuration | Configure Nginx config file
        template:
          src: nginx_kube_dashboard.conf.j2
          dest: /etc/nginx/sites-available/nginx_kube_dashboard.conf
        become: true
        no_log: true
        notify: "restart nginx service"
      - name: Nginx Kube Dashboard Configuration | Enable site config
        file:
          src: "/etc/nginx/sites-available/nginx_kube_dashboard.conf"
          dest: "/etc/nginx/sites-enabled/nginx_kube_dashboard.conf"
          state: link
        become: true
        notify: "restart nginx service"

  - name: Print Dashboard Login Details
    debug:
      msg: "{{ item }}"
    with_items:
      - "Kube Proxy dashboard login url: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/"
      - "Kube Proxy dashboard login token: {{dashboard_login_token.stdout}}"
      - "Kube Nginx Dashboard url: https://{{ ansible_default_ipv4.address }}/"
      - "Kube Nginx Auth user: {{ nginx['dashboard']['admin_username'] }}"
      - "Kube Nginx Auth password: <Please check variable>"
      - "kubectl client configuration file url: https://{{ ansible_default_ipv4.address }}:4433/config"
      - "After downloading config file place it in ~/.kube directory to use kubectl client correctly"