---
  - hosts: all
    roles:
      - common

  - hosts: master
    roles:
      - master

  - hosts: all:!master:!storage
    roles:
      - worker

  - hosts: master
    roles:
      - extra

  - hosts: storage
    roles:
      - nfs-server

  - hosts: all:!storage
    roles:
      - nfs-client
