---
- hosts: all
  roles:
    - role: common

- hosts: storage
  roles:
    - role: nfs-server
      when: not worker_only | bool

- hosts: all:!storage
  roles:
    - role: nfs-client

- hosts: master
  roles:
    - role: master
      when: not worker_only | bool

- hosts: all:!master:!storage
  roles:
    - role: worker

- hosts: master
  roles:
    - role: extra
      when: not worker_only
