apiVersion: v1
kind: Service
metadata:
  name: nginxsvc-wd-sip
  labels:
    app: nginx-wd-sip
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-wd-sip
  clusterIP: 10.254.143.1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: relica-controller-wd-sip
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-wd-sip
    spec:
      containers:
      - name: nginx-wd-sip
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-data-sip
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", 'echo "<center><h1>Welcome to ${HOSTNAME}! </h1></center>" > /usr/share/nginx/html/index.html']
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
      - name: nginx-data-sip
        hostPath:
          path: /data-sip