apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ils-deployment-wd-sip
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx-wd-sip
    spec:
      containers:
      - name: nginx-wd-sip
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-data
      volumes:
      - name: nginx-data
        hostPath:
          path: /data
