---
# tasks file for ansible-nfs-client
  - name: Debian Installation
    include_tasks: debian.yml
    when: ansible_os_family == "Debian"

  - name: Redhat Installation
    include_tasks: redhat.yml
    when: ansible_os_family == "RedHat"

  - name: Configure
    import_tasks: config.yml
