---
  - name: Redhat | Installing NFS Package
    yum:
      name: "nfs-utils"
      state: "present"
    become: true
    when: ansible_distribution != "Fedora"

  - name: Redhat | Installing NFS Package
    dnf:
      name: "nfs-utils"
      state: "present"
    become: true
    when: ansible_distribution == "Fedora"
